### ISSUE TITLE
snowRunner Tool

### ISSUE THREAD

**Issue by Giopolone1** [elpatron68/SnowRunner-Tool#14]
hello, how do I change the path to the program where to get the game backup files?
from: C: \ Program Files (x86) \ Steam \ userdata \ ** 48 *** 20 \ 1465360 \ remote
a: C: \ Program Files (x86) \ Steam \ userdata \ 34 * 92 *** \ 1465360 \ remote
thank you.

**Comment by elpatron68** [comment]
If there are more than one subdirectories under the Steam *userdata* directory, which themselves contain a subdirectory `\1465360\remote` Snowrunner-Tool uses the first in alphabetical order. So, I assume, you have more than one Steam account and play the game with both accounts? If you play the game with just one of your Steam accounts, you should be fine by deleting (or for safety: renaming) the `1465360` subdirectory of the unused account. Otherwise, I´d have to deal with it in one of  the next updates.

**Comment by Giopolone1** [comment]
thanks, i deleted the folder and installed snowrunner tool.

Il giorno sab 19 nov 2022 alle ore 10:23 Markus Busche <
***@***.***> ha scritto:

**Comment by elpatron68** [comment]
Does ist work for you, now?

**Comment by Giopolone1** [comment]
Yes, it works.

Il sab 19 nov 2022, 17:50 Markus Busche ***@***.***> ha
scritto:
